# Generated by Django 2.1 on 2018-11-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181120_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleType',
        ),
        migrations.AddField(
            model_name='article',
            name='articleType_id',
            field=models.IntegerField(choices=[(1, 'python'), (2, 'linux'), (3, '大数据'), (4, '架构'), (5, 'Go')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
