# Generated by Django 2.1 on 2018-11-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181121_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='articleType_id',
        ),
        migrations.AddField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.ArticleType'),
            preserve_default=False,
        ),
    ]
